### ISSUE TITLE
Broken link in part 0

### ISSUE THREAD

**Issue by jibarozzo** [UCSB-MEDS/EDS-296-Intro-to-Shiny#13]
Hi, 

The link to the MEDS Installation Guide in [part 0](https://ucsb-meds.github.io/EDS-296-Intro-to-Shiny/course-materials/part0-setup.html) slides does not work (404 error).  
- https://ucsb-meds.github.io/meds-install-guide.html

I hope this helps.

**Comment by samanthacsik** [comment]
Thanks so much @jibarozzo! We recently moved our installation guide to this URL: https://ucsb-meds.github.io/MEDS-installation-guide/

I'll fix this on my next round of updates :)

**Comment by samanthacsik** [comment]
updated in https://github.com/UCSB-MEDS/EDS-296-Intro-to-Shiny/commit/e74b90cdf82203fdbdb2c8b02a94da431aa916e1!
